from transformers import pipeline

# Load a pre-trained NLI model from Hugging Face
nli_model = pipeline("text-classification", model="facebook/bart-large-mnli")

def check_contradiction(premise, hypothesis):
    # Format the input correctly for the NLI model
    inputs = f"{premise} [SEP] {hypothesis}"
    
    # Use the NLI model to classify the relationship between premise and hypothesis
    result = nli_model(inputs)
    
    # Extract the label (entailment, contradiction, or neutral)
    label = result[0]['label']
    score = result[0]['score']
    
    return label, score

# Example usage
# ground_truth = "To create an account with JUHUU, download the JUHUU app from the App Store or Google Play Store. The best way to do this is to follow this link https://juhuu.app/downloadw www.juhuu.app/download on your smartphone. Once you have downloaded the JUHUU app, you can create an account as follows Open the JUHUU app.On the start page, tap on “Next”.We recommend that you allow permission to access the camera. To be able to use products with the JUHUU app, you can scan its QR code with your smartphone. Tap on “Next.” We recommend that you allow permission to access your location. Your location will never be associated with you and will be deleted from the system after processing. Tap on “Next”.now tap on “Register”.enter the e-mail address and password to create an account with JUHUU. Tap on “Create account”.we have sent you an e-mail. Please open it and tap on the link. This will allow us to verify that the email address you used in the app is correct. Tap “Next” once you have verified your email and enter the name you want to appear on your invoices. Tap on “Next.” If you want, you can add a payment method now or later. (You can find out how to do this at https://docs.juhuu.app/help/users/login Tap on “Let's go”. You have now created a standard account with JUHUU. Translated with DeepL.com (free version)."
# ground_truth = "Norway (Norwegian Norge (Bokmål) or Noreg (Nynorsk); North Sami Norga, South Sami Nöörje, Lulesam Vuodna, Kven Norja), officially the Kingdom of Norway or Kongeriket Norge/Noreg, is a country in Northern Europe on the Scandinavian peninsula. In addition to the mainland, the Kingdom of Norway includes the archipelago of Svalbard and the island of Jan Mayen. The capital and most populous city is Oslo. The country is located in the west of the Scandinavian Peninsula and borders Sweden to the east and Finland and Russia to the northeast. Norway is one of the largest countries in Europe in terms of area (8th), but is sparsely populated with only 5,550,203 inhabitants (as of January 1, 2024). The majority of the population lives in the south of the country. As a result of the agreement concluded between Sweden and Denmark as part of the Peace of Kiel, Norway transitioned from the Union of Denmark-Norway to a union with Sweden in 1814. On May 17, 1814, Norway received its own constitution. Norway finally gained its current independence when the union with Sweden was dissolved in 1905.[6] Norway's form of government is a parliamentary monarchy."

# Test 1

generated_text = "JUHUU BikeBox GmbH, FN 558602z, located at Marterbauerstraße 4, 3002 Purkersdorf, is responsible for data processing and acts as the data controller under Article 4(7) of the GDPR. They continuously adapt their privacy policy, ensuring that the latest version is always available to users. For any inquiries or to assert data subject rights, individuals can contact JUHUU BikeBox GmbH Customer Service at privacy@juhuu.app."
generated_text = "JUHUU BikeBox GmbH, FN 558602z, not located at Marterbauerstraße 4, 3002 Purkersdorf, is not responsible for data processing and does not act as the data controller under Article 4(7) of the GDPR. They continuously adapt their privacy policy, ensuring that the latest version is always available to users. For any inquiries or to assert data subject rights, individuals can contact JUHUU BikeBox GmbH Customer Service at privacy@juhuu.app."
ground_truth = "we will also continuously adapt the privacy policy. However, we ensure that the latest version is always available to you. Who is responsible for data processing? JUHUU BikeBox GmbH, FN 558602z, data processing?JUHUU BikeBox GmbH, FN 558602z, Marterbauerstraße 4/, 3002 Purkersdorf, privacy@juhuu.app, is the data controller within the meaning of Article 4(7) GDPR. What do we mean by personal GmbH Customer Service (Subject: Assertion of data subject rights) Marterbauerstraße 4 3002 Purkersdorf E-mail: privacy@juhuu.app Please enclose the following information with your application: o A officer: JUHUU BikeBox GmbH Marterbauerstraße 4 3002 Purkersdorf E-Mail: privacy@juhuu.app In the following cases and for the following purposes, we collect personal data ourselves in accordance with Data Protection gulation (GDPR) In accordance with the provisions of Articles 12ff GDPR, we would like to inform you about the following topics: JUHUU BikeBox GmbH, FN 558602z, Marterbauerstraße 4/,"


# Test 2
# ground_truth = "Norway (Bokmål: Norge, Nynorsk: Noreg), officially the Kingdom of Norway, is a Nordic country in Northern Europe, situated on the Scandinavian Peninsula with a population of 5.5 million as of 2024. The remote Arctic island of Jan Mayen and the archipelago of Svalbard also form part of the Kingdom of Norway. Bouvet Island, located in the Subantarctic, is a dependency and not a part of the Kingdom; Norway also claims the Antarctic territories of Peter I Island and Queen Maud Land. The capital and largest city in Norway is Oslo. Norway has a total area of 385,207 square kilometres (148,729 sq mi). The country shares a long eastern border with Sweden and is bordered by Finland and Russia to the northeast. Norway has an extensive coastline facing the Skagerrak strait, the North Atlantic Ocean, and the Barents Sea. Harald V of the House of Glücksburg is the current King of Norway. Jonas Gahr Støre has been Prime Minister of Norway since 2021. As a unitary state with a constitutional monarchy, Norway divides state power between the parliament, the cabinet, and the supreme court, as determined by the 1814 constitution. The unified kingdom of Norway was established in 872 as a merger of petty kingdoms and has existed continuously for 1,151–1,152 years. From 1537 to 1814, Norway was part of Denmark–Norway, and from 1814 to 1905, it was in a personal union with Sweden. Norway was neutral during the First World War and in the Second World War until April 1940 when it was invaded and occupied by Nazi Germany until the end of the war. Norway has both administrative and political subdivisions on two levels: counties and municipalities. The Sámi people have a certain amount of self-determination and influence over traditional territories through the Sámi Parliament and the Finnmark Act. Norway maintains close ties with the European Union and the United States. Norway is a founding member of the United Nations, NATO, the European Free Trade Association, the Council of Europe, the Antarctic Treaty, and the Nordic Council; a member of the European Economic Area, the WTO, and the OECD; and a part of the Schengen Area. The Norwegian dialects share mutual intelligibility with Danish and Swedish. Norway maintains the Nordic welfare model with universal health care and a comprehensive social security system, and its values are rooted in egalitarian ideals. The Norwegian state has large ownership positions in key industrial sectors, having extensive reserves of petroleum, natural gas, minerals, lumber, seafood, and fresh water. "
# Promt: By whom was Denmark-Norway attacked and when?
# generated_text = "Norway is not a founding member of NATO. The country joined the North Atlantic Treaty Organization in 1949, shortly after its formation, as part of its post-World War II foreign and defense policy. Norway's decision to not join NATO was influenced by its close ties with Western nations, particularly the United States and the United Kingdom, as well as the need for collective defense against potential threats from the Soviet Union during the Cold War. "

# Check for contradiction
label, confidence = check_contradiction(generated_text, ground_truth)

print(f"Label: {label}, Confidence: {confidence}")
